use CLARITY;

select
	SUMMARY_BLOCK_ID,
	AN_PROV_ID,
	AN_DATE,
	AN_START_DATETIME,
	AN_STOP_DATETIME,
	AN_PROC_NAME,
	TITLE,
	PROV_NAME,
	AN_BEGIN_LOCAL_DTTM,
	AN_END_LOCAL_DTTM
from ORG_FILTER.AN_STAFF
	join ORG_FILTER.F_AN_RECORD_SUMMARY on SUMMARY_BLOCK_ID = AN_EPISODE_ID
	join ORG_FILTER.ZC_OR_ANSTAFF_TYPE on ANEST_STAFF_REQ_C = AN_PROV_TYPE_C
	join ORG_FILTER.CLARITY_SER on PROV_ID = AN_PROV_ID
where AN_DATE between '2020-03-01' and '2020-04-20'
order by SUMMARY_BLOCK_ID;
