// flow-typed signature: 6d9f7bfe495a5ad24e3ac5237e597dcb
// flow-typed version: <<STUB>>/gulp-file-contents-to-json_v^0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-file-contents-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-file-contents-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-file-contents-to-json/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-file-contents-to-json/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-file-contents-to-json/gulpfile.js' {
  declare module.exports: $Exports<'gulp-file-contents-to-json/gulpfile'>;
}
declare module 'gulp-file-contents-to-json/index' {
  declare module.exports: $Exports<'gulp-file-contents-to-json'>;
}
declare module 'gulp-file-contents-to-json/index.js' {
  declare module.exports: $Exports<'gulp-file-contents-to-json'>;
}
declare module 'gulp-file-contents-to-json/test.js' {
  declare module.exports: $Exports<'gulp-file-contents-to-json/test'>;
}
