// flow-typed signature: 5de456cdd3301850c3d64cacabc02a1f
// flow-typed version: <<STUB>>/gulp-each_v^0.5.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-each'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-each' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-each/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-each/index' {
  declare module.exports: $Exports<'gulp-each'>;
}
declare module 'gulp-each/index.js' {
  declare module.exports: $Exports<'gulp-each'>;
}
declare module 'gulp-each/test.js' {
  declare module.exports: $Exports<'gulp-each/test'>;
}
