// flow-typed signature: 74a710ca2bf6c3dc474aab8c20222f84
// flow-typed version: <<STUB>>/indefinite_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'indefinite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'indefinite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'indefinite/dist/indefinite' {
  declare module.exports: any;
}

declare module 'indefinite/dist/indefinite.min' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/clean' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/codeclimate' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/config' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/copy' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/cover' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/instrument' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/karma' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/lint' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/open' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/uglify' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/unit' {
  declare module.exports: any;
}

declare module 'indefinite/gulp/watch' {
  declare module.exports: any;
}

declare module 'indefinite/gulpfile' {
  declare module.exports: any;
}

declare module 'indefinite/karma.conf' {
  declare module.exports: any;
}

declare module 'indefinite/lib/indefinite' {
  declare module.exports: any;
}

declare module 'indefinite/test/helpers/require' {
  declare module.exports: any;
}

declare module 'indefinite/test/helpers/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'indefinite/dist/indefinite.js' {
  declare module.exports: $Exports<'indefinite/dist/indefinite'>;
}
declare module 'indefinite/dist/indefinite.min.js' {
  declare module.exports: $Exports<'indefinite/dist/indefinite.min'>;
}
declare module 'indefinite/gulp/clean.js' {
  declare module.exports: $Exports<'indefinite/gulp/clean'>;
}
declare module 'indefinite/gulp/codeclimate.js' {
  declare module.exports: $Exports<'indefinite/gulp/codeclimate'>;
}
declare module 'indefinite/gulp/config.js' {
  declare module.exports: $Exports<'indefinite/gulp/config'>;
}
declare module 'indefinite/gulp/copy.js' {
  declare module.exports: $Exports<'indefinite/gulp/copy'>;
}
declare module 'indefinite/gulp/cover.js' {
  declare module.exports: $Exports<'indefinite/gulp/cover'>;
}
declare module 'indefinite/gulp/instrument.js' {
  declare module.exports: $Exports<'indefinite/gulp/instrument'>;
}
declare module 'indefinite/gulp/karma.js' {
  declare module.exports: $Exports<'indefinite/gulp/karma'>;
}
declare module 'indefinite/gulp/lint.js' {
  declare module.exports: $Exports<'indefinite/gulp/lint'>;
}
declare module 'indefinite/gulp/open.js' {
  declare module.exports: $Exports<'indefinite/gulp/open'>;
}
declare module 'indefinite/gulp/uglify.js' {
  declare module.exports: $Exports<'indefinite/gulp/uglify'>;
}
declare module 'indefinite/gulp/unit.js' {
  declare module.exports: $Exports<'indefinite/gulp/unit'>;
}
declare module 'indefinite/gulp/watch.js' {
  declare module.exports: $Exports<'indefinite/gulp/watch'>;
}
declare module 'indefinite/gulpfile.js' {
  declare module.exports: $Exports<'indefinite/gulpfile'>;
}
declare module 'indefinite/karma.conf.js' {
  declare module.exports: $Exports<'indefinite/karma.conf'>;
}
declare module 'indefinite/lib/indefinite.js' {
  declare module.exports: $Exports<'indefinite/lib/indefinite'>;
}
declare module 'indefinite/test/helpers/require.js' {
  declare module.exports: $Exports<'indefinite/test/helpers/require'>;
}
declare module 'indefinite/test/helpers/setup.js' {
  declare module.exports: $Exports<'indefinite/test/helpers/setup'>;
}
