// flow-typed signature: 9801eee60afff71e4b94ae46577c12b7
// flow-typed version: <<STUB>>/laravel-elixir_v^6.0.0-15/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'laravel-elixir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'laravel-elixir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'laravel-elixir/dist/bootstrap/EnableExtension' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/bootstrap/LoadExtensions' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/bootstrap/SetDependencies' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/bootstrap/SetHooks' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/Config' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/index' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/Log' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/Notification' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/reporters/MinimalTaskReporter' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/reporters/TaskReporter' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/CombineTask' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/CssTask' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/GulpBuilder' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/GulpPaths' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/combine' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/copy' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/default' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/deprecated' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/exec' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/external-recipes' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/less' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/phpspec' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/phpunit' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/sass' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/scripts' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/styles' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/task' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/tdd' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/version' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/recipes/watch' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/Task' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/TaskCollection' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/TestingTask' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/utilities/minifier' {
  declare module.exports: any;
}

declare module 'laravel-elixir/dist/tasks/VersionTask' {
  declare module.exports: any;
}

// Filename aliases
declare module 'laravel-elixir/dist/bootstrap/EnableExtension.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/bootstrap/EnableExtension'>;
}
declare module 'laravel-elixir/dist/bootstrap/LoadExtensions.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/bootstrap/LoadExtensions'>;
}
declare module 'laravel-elixir/dist/bootstrap/SetDependencies.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/bootstrap/SetDependencies'>;
}
declare module 'laravel-elixir/dist/bootstrap/SetHooks.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/bootstrap/SetHooks'>;
}
declare module 'laravel-elixir/dist/Config.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/Config'>;
}
declare module 'laravel-elixir/dist/index.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/index'>;
}
declare module 'laravel-elixir/dist/Log.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/Log'>;
}
declare module 'laravel-elixir/dist/Notification.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/Notification'>;
}
declare module 'laravel-elixir/dist/reporters/MinimalTaskReporter.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/reporters/MinimalTaskReporter'>;
}
declare module 'laravel-elixir/dist/reporters/TaskReporter.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/reporters/TaskReporter'>;
}
declare module 'laravel-elixir/dist/tasks/CombineTask.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/CombineTask'>;
}
declare module 'laravel-elixir/dist/tasks/CssTask.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/CssTask'>;
}
declare module 'laravel-elixir/dist/tasks/GulpBuilder.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/GulpBuilder'>;
}
declare module 'laravel-elixir/dist/tasks/GulpPaths.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/GulpPaths'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/combine.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/combine'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/copy.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/copy'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/default.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/default'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/deprecated.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/deprecated'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/exec.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/exec'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/external-recipes.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/external-recipes'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/less.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/less'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/phpspec.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/phpspec'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/phpunit.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/phpunit'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/sass.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/sass'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/scripts.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/scripts'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/styles.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/styles'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/task.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/task'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/tdd.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/tdd'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/version.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/version'>;
}
declare module 'laravel-elixir/dist/tasks/recipes/watch.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/recipes/watch'>;
}
declare module 'laravel-elixir/dist/tasks/Task.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/Task'>;
}
declare module 'laravel-elixir/dist/tasks/TaskCollection.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/TaskCollection'>;
}
declare module 'laravel-elixir/dist/tasks/TestingTask.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/TestingTask'>;
}
declare module 'laravel-elixir/dist/tasks/utilities/minifier.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/utilities/minifier'>;
}
declare module 'laravel-elixir/dist/tasks/VersionTask.js' {
  declare module.exports: $Exports<'laravel-elixir/dist/tasks/VersionTask'>;
}
