// flow-typed signature: 123ad34446b940369cb8064a8dec6097
// flow-typed version: <<STUB>>/twix_v^1.1.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'twix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

import type moment$Moment from 'moment';

declare module 'twix' {
	declare class twix$Twix {
		isValid(): boolean;
		isSame(t: twix$Twix): boolean;
		isPast(): boolean;
		isFuture(): boolean;
		isCurrent(): boolean;
		contains(d: moment$Moment): boolean;
		length(t: string): number;
		count(t: string): number;
		countInner(t: string): number;
		iterate(t: string): twix$Iterator;
		iterateInner(t: string): twix$Iterator;

		toArray(): Array<moment$Moment>;
		start(): moment$Moment;
		end(): moment$Moment;
	}

	declare class twix$Iterator {
		hasNext(): boolean;
		next(): moment$Moment;
	}

	declare export default Class<twix$Twix>;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'twix/dist/twix' {
	declare module.exports: $Exports<'twix'>;
}

declare module 'twix/dist/twix.min' {
	declare module.exports: $Exports<'twix'>;
}

declare module 'twix/package' {
	declare module.exports: $Exports<'twix'>;
}

// Filename aliases
declare module 'twix/dist/twix.js' {
	declare module.exports: $Exports<'twix/dist/twix'>;
}
declare module 'twix/dist/twix.min.js' {
	declare module.exports: $Exports<'twix/dist/twix.min'>;
}
declare module 'twix/package.js' {
	declare module.exports: $Exports<'twix/package'>;
}
