// flow-typed signature: 75b26a4b3277fe4e1a6c39a8221fa6d8
// flow-typed version: <<STUB>>/v-tooltip_v^2.0.0-beta.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'v-tooltip/config/webpack.config.base' {
  declare module.exports: any;
}

declare module 'v-tooltip/config/webpack.config.browser' {
  declare module.exports: any;
}

declare module 'v-tooltip/config/webpack.config.common' {
  declare module.exports: any;
}

declare module 'v-tooltip/config/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'v-tooltip/demo-src/src/main' {
  declare module.exports: any;
}

declare module 'v-tooltip/demo-src/webpack.config' {
  declare module.exports: any;
}

declare module 'v-tooltip/dist/v-tooltip.browser' {
  declare module.exports: any;
}

declare module 'v-tooltip/dist/v-tooltip.common' {
  declare module.exports: any;
}

declare module 'v-tooltip/docs/build' {
  declare module.exports: any;
}

declare module 'v-tooltip/src/index' {
  declare module.exports: any;
}

declare module 'v-tooltip/src/utils' {
  declare module.exports: any;
}

declare module 'v-tooltip/src/v-tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'v-tooltip/config/webpack.config.base.js' {
  declare module.exports: $Exports<'v-tooltip/config/webpack.config.base'>;
}
declare module 'v-tooltip/config/webpack.config.browser.js' {
  declare module.exports: $Exports<'v-tooltip/config/webpack.config.browser'>;
}
declare module 'v-tooltip/config/webpack.config.common.js' {
  declare module.exports: $Exports<'v-tooltip/config/webpack.config.common'>;
}
declare module 'v-tooltip/config/webpack.config.dev.js' {
  declare module.exports: $Exports<'v-tooltip/config/webpack.config.dev'>;
}
declare module 'v-tooltip/demo-src/src/main.js' {
  declare module.exports: $Exports<'v-tooltip/demo-src/src/main'>;
}
declare module 'v-tooltip/demo-src/webpack.config.js' {
  declare module.exports: $Exports<'v-tooltip/demo-src/webpack.config'>;
}
declare module 'v-tooltip/dist/v-tooltip.browser.js' {
  declare module.exports: $Exports<'v-tooltip/dist/v-tooltip.browser'>;
}
declare module 'v-tooltip/dist/v-tooltip.common.js' {
  declare module.exports: $Exports<'v-tooltip/dist/v-tooltip.common'>;
}
declare module 'v-tooltip/docs/build.js' {
  declare module.exports: $Exports<'v-tooltip/docs/build'>;
}
declare module 'v-tooltip/src/index.js' {
  declare module.exports: $Exports<'v-tooltip/src/index'>;
}
declare module 'v-tooltip/src/utils.js' {
  declare module.exports: $Exports<'v-tooltip/src/utils'>;
}
declare module 'v-tooltip/src/v-tooltip.js' {
  declare module.exports: $Exports<'v-tooltip/src/v-tooltip'>;
}
