// flow-typed signature: c61106d34a7f03b727177e0e371d7643
// flow-typed version: <<STUB>>/@jacobmischka/transform-color_v^1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jacobmischka/transform-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jacobmischka/transform-color' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jacobmischka/transform-color/dist/index.cjs' {
  declare module.exports: any;
}

declare module '@jacobmischka/transform-color/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jacobmischka/transform-color/dist/index.cjs.js' {
  declare module.exports: $Exports<'@jacobmischka/transform-color/dist/index.cjs'>;
}
declare module '@jacobmischka/transform-color/dist/index.js' {
  declare module.exports: $Exports<'@jacobmischka/transform-color/dist/index'>;
}
