// flow-typed signature: 633a0bec903a97c248ababbc7313f5a0
// flow-typed version: <<STUB>>/@jacobmischka/vue-flatpickr_v2.2.11/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jacobmischka/vue-flatpickr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jacobmischka/vue-flatpickr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jacobmischka/vue-flatpickr/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jacobmischka/vue-flatpickr/dist/index.js' {
  declare module.exports: $Exports<'@jacobmischka/vue-flatpickr/dist/index'>;
}
