on: push
name: Build and deploy
jobs:
  master:
    name: Master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: maddox/actions/ssh@master
      uses: maddox/actions/ssh@master
      env:
        HOST: ${{ secrets.HOST }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        USER: ${{ secrets.USER }}
      with:
        args: /root/update.sh
